# Generated by Django 5.2 on 2025-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailverification_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Routine', 'Routine'), ('Fitness', 'Fitness')], default='Personal', max_length=20),
        ),
    ]
