# Generated by Django 5.2 on 2025-04-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
